### ISSUE TITLE
Source , Image Source Field in Post

### ISSUE THREAD

**Issue by fareed543** [Snopzer/techdefeat#2]
For every post we copy it from one place, We want to clearly specify that where exactly its originally published at
So, Here are the some Related work we have to enhance

1. Add 2 Text Fields in Post Table 'source','image_source'
2. Add Source , Image Source Field in both add & edit pages

Image issue.
When Image not Uploading in Post, Some value storing in the image field, which leads to and image error appearing in the browser.
Please check in admin,
and Test When image not upload , how blank image appearing in the Front-end

**Comment by wahd6** [comment]
'source','image_source'   what do you want to store in this   text/image  or both text/text

**Comment by wahd6** [comment]
Added feilds to db and added to add/edit page.
   1. Add 2 Text Fields in Post Table 'source','image_source'
    2.Add Source , Image Source Field in both add & edit pages
