### ISSUE TITLE
Stuff Still at DB

### ISSUE THREAD

**Issue by fareed543** [Snopzer/techdefeat#6]
When we Delete the post Record from DB, We should also delete the Related Stuff from the SEO URL Table
i did it for post.

Similarly we have to remove it for Other Like Users. Category and Question ect.

**Note:  Deleting something means, Delete the related Stuff from DB and from file System.**

**Comment by wahd6** [comment]
Added to Users Questions And categories.  reamain all pages we dont have seo url if we have let know
