### ISSUE TITLE
Issue when mail Id is entering 

### ISSUE THREAD

**Issue by asmafareed** [Snopzer/techdefeat#8]
When entering the mail id .com is coming out of the space provided to it
So correction of the issue should be done to over through the problem 
![screenshot_2016-09-30-15-28-02](https://cloud.githubusercontent.com/assets/22454620/18989460/c5576198-8729-11e6-8103-ed264a6ff73c.jpeg)

**Comment by fareed543** [comment]
Resolved all Similar kinds of issue in Mobile.
Please Test them Again, let me know the if you have any Queries
